# Generated by Django 5.1.2 on 2024-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='store_carti_cart_id_1ecc31_idx',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'quantity'], name='store_carti_cart_id_e27765_idx'),
        ),
    ]
