# Generated by Django 5.1.2 on 2024-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='store_carti_cart_id_e27765_idx',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='store_carti_cart_id_1ecc31_idx'),
        ),
    ]
