image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: docker
  LOG_FILE_NAME: gitlab_logs.txt
  DB_USER: postgres
  DB_NAME: ecommerce
  REPLICA_USER: replica

before_script:
  - apk add --no-cache py-pip
  - echo "Logging in to Docker registry..."
  - docker login -u gitlab-ci-token -p $CI_ACCESS_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Start Building ..."
    - docker-compose build
    - docker-compose push
    - echo "End Building."

test:
  stage: test
  script:
    - echo "Start Testing ..."
    - docker-compose up -d
    - docker-compose exec web1 python manage.py test
    - echo "End Testing."

deploy:
  stage: deploy
  script:
    - echo "Start Deploying"
    - docker-compose run --rm web1 python manage.py makemigrations
    - docker-compose run --rm web1 python manage.py migrate
    - echo "Granting SELECT privileges on primary DB to replicas"
    - |
      docker-compose exec -T db psql -U $DB_USER -d $DB_NAME -c "
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO $REPLICA_USER;
      "
    - echo "End Deploying"
