image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  LOG_FILE_NAME: gitlab_logs.txt
  DB_USER: postgres
  DB_NAME: ecommerce
  DB_CONTAINER: primary-db 
  REPLICA_USER: replica
  ENV_PATH: ./core/config/.env

before_script:
  - apk add --no-cache py-pip
  - echo "Logging in to Docker registry..."
  - docker login -u gitlab-ci-token -p $CI_ACCESS_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Start Building ..."
    - docker-compose build
    - docker-compose push
    - echo "End Building."

test:
  stage: test
  script:
    - echo "Start Testing ..."
    - docker-compose --env-file $ENV_PATH up -d
    - docker-compose exec web1 python manage.py test
    - echo "End Testing."
  after_script:
    - docker-compose down

deploy:
  stage: deploy
  script:
    - echo "Start Deploying"
    - docker-compose --env-file $ENV_PATH run --rm web1 python manage.py makemigrations
    - docker-compose --env-file $ENV_PATH run --rm web1 python manage.py migrate
    - echo "End Deploying"
