# image: docker:latest
# services:
#   - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: docker
  LOG_FILE_NAME: gitlab_logs.txt

# before_script:
#   - apk add --no-cache py-pip
#   - pip install docker-compose==1.9.0
#   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    # Uncomment these lines if you are using docker-compose
    # - docker-compose build
    # - docker-compose push
    - echo "building" >> ${LOG_FILE_NAME}

test:
  stage: test
  script:
    # Uncomment these lines if you are using docker-compose
    # - docker-compose pull test
    # - docker-compose run test 
    - echo "testing" >> ${LOG_FILE_NAME}

deploy:
  stage: deploy
  script:
    - echo "deploying" >> ${LOG_FILE_NAME}
