input {
  file {
    path => "debug.log" 
    start_position => "beginning"
  }
}

filter {
  
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }
}
